# Generated by Django 3.1.7 on 2021-03-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
