# Generated by Django 3.1.7 on 2021-03-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='q',
            field=models.IntegerField(default=0),
        ),
    ]
